/**
 * QYNTRA GENERATED TEST
 *
 * Requirement : User can log in to the Peak platform
 * Application : Peak
 * URL         : https://platform.peak.ai/login
 *
 * Scenario    : Invalid Credentials
 * Priority    : P0
 * Type        : Negative
 * Capability  : Authentication
 *
 * Generated by Qyntra Test Generator v3
 */

import { test, expect } from '@playwright/test';

// Session saved by `qyntra login` / `qyntra run` for apps behind a login.
// Conditional so a storageState in playwright.config.ts is not overridden.
if (process.env.QYNTRA_STORAGE_STATE) {
  test.use({ storageState: process.env.QYNTRA_STORAGE_STATE });
}

test('Invalid Credentials', async ({ page }) => {
  await page.goto("https://platform.peak.ai/login");

  const identifier = page.getByLabel("Organization name", { exact: true });
  const submit = page.getByRole('button', { name: "Continue", exact: true });

  await expect(identifier).toBeVisible();
  const token = Math.random().toString(36).slice(2, 8);

  await identifier.fill(`qyntra-probe-${token}`);
  await submit.click();

  await expect(page.getByText("Invalid organization name").first()).toBeVisible({ timeout: 10_000 });
  await expect(page).toHaveURL(/^https:\/\/platform\.peak\.ai\/login/);
  await expect(identifier).toBeVisible();
});
